### ISSUE TITLE
nginx.conf error

### ISSUE THREAD

**Issue by Hristovnews** [racompton/routinator_centos7_install#1]
Great guide , everything works fine except nginx .
When i start the nginx server , process  fails with :  nginx: [emerg] unknown directive "<!DOCTYPE" in /etc/nginx/nginx.conf:58 
I did reinstall nginx , but same result with the clean installation .

**Comment by racompton** [comment]
I didn't see "<!DOCTYPE" in the nginx.conf file.  Maybe you pulled down the HTML page for that doc instead of the raw code?  Does your nginx.conf file have "<!DOCTYPE" on line 58?  You can get the raw version by doing "wget https://raw.githubusercontent.com/racompton/routinator_centos7_install/master/nginx.conf"

**Comment by Hristovnews** [comment]
Yep , 
Thank you Rich . Wrong urls  , (both  files were corrupted by me , having wget the link :(  )Now everything seems to be perfect :  Active: active (running) since Thu 2021-03-04 19:47:27 EET; 5s agoRTR session is ok  (it was before).
Please close/delete the issue .
Have a nice day/night 
Best Regards Hristo HristovI     On Thursday, March 4, 2021, 07:20:58 PM GMT+2, Rich Compton <notifications@github.com> wrote:  
 
 


I didn't see "<!DOCTYPE" in the nginx.conf file. Maybe you pulled down the HTML page for that doc instead of the raw code? Does your nginx.conf file have "<!DOCTYPE" on line 58? You can get the raw version by doing "wget https://raw.githubusercontent.com/racompton/routinator_centos7_install/master/nginx.conf"

**Comment by racompton** [comment]
Great, glad that I could help.  FYI, I believe that the NLNet Lab's folks will be creating an RPM repository for routinator and krill in the next month or so.
